name: keepalive-direct
on:
  schedule:
    - cron: "5 19 * * *"   # 매일 KST 새벽 04:05 (UTC 19:05)
  workflow_dispatch: {}     # 수동 실행 버튼도 추가

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: https://zcdwskarhmexxrivpgjw.supabase.co
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - name: Call Supabase RPC directly
        run: |
          curl -sS \
            -H "apikey: $SUPABASE_ANON_KEY" \
            -H "Authorization: Bearer $SUPABASE_ANON_KEY" \
            -H "Content-Type: application/json" \
            -X POST \
            "$SUPABASE_URL/rest/v1/rpc/heartbeat" \
            -d '{}' || exit 1
